---
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network: host  # Nur für DLNA notwendig
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/jellyfin/config:/config
      - /var/docker/jellyfin/cache:/cache
      - <path>:/data  # Den Pfad bitte so setzen, dass Jellyfin an eure Medien ran kommt
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}
