name: "Create compose files summary"

concurrency: compose-files

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "compose-files/**"

jobs:
  generate-summary:
    name: Auto-generate charts summary
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.COMPOSE_APP_ID }}
          private_key: ${{ secrets.COMPOSE_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: master
          fetch-depth: 0

      - name: Install yq
        uses: chrisdickinson/setup-yq@latest
        with:
          yq-version: v4.9.3

      - name: Run script
        run: |
          ./hack/gen-compose-summary.sh
      - name: Create Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          commit_message: Auto-generate compose summary [no ci]
          commit_user_name: cbirkenbeul[bot]
          commit_user_email: cbirkenbeul[bot]@users.noreply.github.com
          commit_author: cbirkenbeul[bot] <cbirkenbeul[bot]@users.noreply.github.com>
          file_pattern: compose-files/README.md